apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ (index .Values.redis.ports 0).port }}
      targetPort: {{ (index .Values.redis.ports 0).targetPort }}
  type: ClusterIP