apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-deployment
spec:
  replicas: {{ .Values.queue.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: queue
          image: {{ .Values.queue.image.repository }}:{{ .Values.queue.image.tag }}
          imagePullPolicy: Always
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "300Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "1024Mi"
          ports:
            - containerPort: {{ (index .Values.queue.ports 0).port }}