apiVersion: v1
kind: Service
metadata:
  name: queue-server
spec:
  selector:
    app: queue
  ports:
    - protocol: TCP
      port: {{ (index .Values.queue.ports 0).port }}
      targetPort: {{ (index .Values.queue.ports 0).targetPort }}
      # nodePort: {{ (index .Values.queue.ports 0).nodePort }}
  type: ClusterIP