apiVersion: apps/v1
kind: Deployment
metadata:
  name: concerts-deployment
spec:
  replicas: {{ .Values.concerts.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: concerts
  template:
    metadata:
      labels:
        app: concerts
    spec:
      containers:
        - name: concerts
          image: bhkhk/main-concerts-server:16
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "300Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "1024Mi"
          ports:
            - containerPort: {{ (index .Values.concerts.ports 0).port }}