apiVersion: apps/v1
kind: Deployment
metadata:
  name: concerts-deployment
spec:
  replicas: {{ .Values.concerts.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: concerts
  template:
    metadata:
      annotations:
        argocd-image-updater.argoproj.io/image-list: {{ .Values.concerts.image.repository }}
        argocd-image-updater.argoproj.io/update-strategy: latest/nuwest-build
      labels:
        app: concerts
    spec:
      containers:
        - name: concerts
          imagePullPolicy: Always
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "300Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "1024Mi"
          ports:
            - name: http
              containerPort: {{ (index .Values.concerts.ports 0).port }}
              protocol: TCP
  