apiVersion: apps/v1
kind: Deployment
metadata:
  name: concert-deployment
spec:
  replicas: {{ .Values.concert.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: concert
  template:
    metadata:
      labels:
        app: concert
    spec:
      containers:
        - name: concert
          image: {{ .Values.concert.image.repository }}
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "300Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "1024Mi"
          ports:
            - containerPort: {{ (index .Values.concert.ports 0).port }}