apiVersion: v1
kind: Service
metadata:
  name: concerts-server
spec:
  selector:
    app: concerts
  ports:
    - protocol: TCP
      port: {{ (index .Values.concerts.ports 0).port }}
      targetPort: {{ (index .Values.concerts.ports 0).targetPort }}
      # nodePort: {{ (index .Values.concerts.ports 0).nodePort }}
  type: ClusterIP