apiVersion: v1
kind: Service
metadata:
  name: concerts-server
spec:
  selector:
    app: concerts
  ports:
    - protocol: TCP
      port: {{ (index .Values.concert.ports 0).port }}
      targetPort: {{ (index .Values.concert.ports 0).targetPort }}
  type: ClusterIP