apiVersion: v1
kind: Service
metadata:
  name: concert-backend-service
spec:
  selector:
    app: concert-backend
  ports:
    - protocol: TCP
      port: {{ (index .Values.concert-backend.ports 0).port }}
      targetPort: {{ (index .Values.concert-backend.ports 0).targetPort }}
  type: ClusterIP