apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate-deployment
spec:
  replicas: {{ .Values.gate.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: gate
  template:
    metadata:
      labels:
        app: gate
    spec:
      containers:
        - name: gate
          image: {{ .Values.gate.image.repository }}:{{ .Values.gate.image.tag }}
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "300Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "1024Mi"
          ports:
            - containerPort: {{ (index .Values.gate.ports 0).port }}