apiVersion: v1
kind: Service
metadata:
  name: gate-server
spec:
  selector:
    app: gate
  ports:
    - protocol: TCP
      port: {{ (index .Values.gate.ports 0).port }}
      targetPort: {{ (index .Values.gate.ports 0).targetPort }}
      nodePort: 30003
  type: NodePort