apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: {{ .Values.admin.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: bhkhk/main-admin-server:latest
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "300Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "1024Mi"
          ports:
            - containerPort: {{ (index .Values.admin.ports 0).port }}