apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: {{ (index .Values.admin.ports 0).port }}
      targetPort: {{ (index .Values.admin.ports 0).targetPort }}
      nodePort: 30001
  type: NodePort