apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: {{ .Values.user.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: {{ .Values.user.image.repository }}:{{ .Values.user.image.tag }}
          imagePullPolicy: Always
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "300Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "1024Mi"
          ports:
            - containerPort: {{ (index .Values.user.ports 0).port }}