apiVersion: v1
kind: Service
metadata:
  name: user-server
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: {{ (index .Values.user.ports 0).port }}
      targetPort: {{ (index .Values.user.ports 0).targetPort }}
      # nodePort: {{ (index .Values.user.ports 0).nodePort }}
  type: ClusterIP