concerts:
  enabled: true
  replicas: 2
  ports:
    - name: concerts
      port: 5000
      targetPort: 5000
      nodePort: 30005
  image:
    repository: bhkhk/main-concerts-server
    tags: latest