apiVersion: apps/v1
kind: Deployment
metadata:
  name: concertdb-deployment
spec:
  replicas: {{ .Values.concertdb.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: concertdb
  template:
    metadata:
      labels:
        app: concertdb
    spec:
      containers:
        - name: concerts-server-db
          image: {{ .Values.concertdb.image.repository }}
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "300Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "1024Mi"
          ports:
            - containerPort: {{ (index .Values.concertdb.ports 0).port }}