apiVersion: apps/v1
kind: Deployment
metadata:
  name: concerts-server-db-deployment
spec:
  replicas: {{ .Values.concertsdb.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: concertsdb
  template:
    metadata:
      labels:
        app: concertsdb
    spec:
      containers:
        - name: concerts-server-db
          image: {{ .Values.concertsdb.image.repository }}:{{ .Values.concertsdb.image.tag }}
          imagePullPolicy: Always
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "300Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "1024Mi"
          ports:
            - containerPort: {{ (index .Values.concertsdb.ports 0).port }}