apiVersion: v1
kind: Service
metadata:
  name: concert-db-service
spec:
  selector:
    app: concert-db
  ports:
    - protocol: TCP
      port: {{ (index .Values.concert-db.ports 0).port }}
      targetPort: {{ (index .Values.concert-db.ports 0).targetPort }}
  type: ClusterIP