apiVersion: v1
kind: Service
metadata:
  name: concerts-server-db
spec:
  selector:
    app: concertsdb
  ports:
    - protocol: TCP
      port: {{ (index .Values.concertsdb.ports 0).port }}
      targetPort: {{ (index .Values.concertsdb.ports 0).targetPort }}
  type: ClusterIP