apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: {{ (index .Values.web.ports 0).port }}
      targetPort: {{ (index .Values.web.ports 0).targetPort }}
      nodePort: 30000
